export const statusColors: Record<string, string> = {
  pending: 'bg-amber-100 text-amber-700',
  scanning: 'bg-blue-100 text-blue-700',
  allocating: 'bg-purple-100 text-purple-700',
  stacking: 'bg-indigo-100 text-indigo-700',
  completed: 'bg-green-100 text-green-700',
  idle: 'bg-gray-100 text-gray-700',
  running: 'bg-blue-100 text-blue-700',
  moving: 'bg-blue-100 text-blue-700',
  loading: 'bg-purple-100 text-purple-700',
  charging: 'bg-amber-100 text-amber-700',
  fault: 'bg-red-100 text-red-700',
  failed: 'bg-red-100 text-red-700',
  maintenance: 'bg-gray-100 text-gray-700',
  empty: 'bg-gray-100 text-gray-600',
  occupied: 'bg-green-100 text-green-700',
  reserved: 'bg-amber-100 text-amber-700',
  stored: 'bg-green-100 text-green-700',
  picking: 'bg-blue-100 text-blue-700',
  reviewing: 'bg-purple-100 text-purple-700',
  processing: 'bg-blue-100 text-blue-700',
  normal: 'bg-gray-100 text-gray-700',
  urgent: 'bg-orange-100 text-orange-700',
  vip: 'bg-purple-100 text-purple-700',
  periodic: 'bg-blue-100 text-blue-700',
  random: 'bg-green-100 text-green-700',
  special: 'bg-purple-100 text-purple-700',
  active: 'bg-red-100 text-red-700',
  handled: 'bg-green-100 text-green-700',
  ignored: 'bg-gray-100 text-gray-600',
  low_stock: 'bg-red-100 text-red-700',
  high_stock: 'bg-orange-100 text-orange-700',
  obsolete: 'bg-gray-100 text-gray-700',
  expiry: 'bg-amber-100 text-amber-700',
  inbound: 'bg-green-100 text-green-700',
  outbound: 'bg-blue-100 text-blue-700',
  transfer: 'bg-purple-100 text-purple-700',
  executing: 'bg-blue-100 text-blue-700',
  adjust: 'bg-yellow-100 text-yellow-700',
  check: 'bg-cyan-100 text-cyan-700',
  execute: 'bg-blue-100 text-blue-700',
  dispatch: 'bg-purple-100 text-purple-700',
  pause: 'bg-amber-100 text-amber-700',
  cancel: 'bg-red-100 text-red-700',
  complete: 'bg-green-100 text-green-700',
}

export const statusLabels: Record<string, string> = {
  pending: '待处理',
  scanning: '扫码中',
  allocating: '分配中',
  stacking: '上架中',
  completed: '已完成',
  idle: '空闲',
  running: '运行中',
  moving: '移动中',
  loading: '装载中',
  charging: '充电中',
  fault: '故障',
  failed: '失败',
  maintenance: '维护中',
  empty: '空',
  occupied: '占用',
  reserved: '预留',
  stored: '已存储',
  picking: '拣选中',
  reviewing: '复核中',
  processing: '处理中',
  normal: '普通',
  urgent: '紧急',
  vip: 'VIP',
  periodic: '定期盘点',
  random: '随机盘点',
  special: '专项盘点',
  active: '待处理',
  handled: '已处理',
  ignored: '已忽略',
  low_stock: '库存不足',
  high_stock: '库存过高',
  obsolete: '呆滞库存',
  expiry: '临期预警',
  inbound: '入库',
  outbound: '出库',
  transfer: '移库',
  adjust: '库存调整',
  check: '盘点',
  executing: '执行中',
  execute: '执行',
  dispatch: '调度',
  pause: '暂停',
  cancel: '取消',
  complete: '完成',
}

export function formatDate(dateStr: string): string {
  return dateStr
}

export function generateCode(prefix: string, num: number): string {
  return prefix + String(num).padStart(6, '0')
}
